full pipeline

diff --git a/.github/workflows/pipeline.yml b/.github/workflows/pipeline.yml
--- a/.github/workflows/pipeline.yml
+++ b/.github/workflows/pipeline.yml
@@ -6,230 +6,230 @@ on:
       - main
 
 jobs:
-  # lint:
-  #   runs-on: ubuntu-latest
+  lint:
+    runs-on: ubuntu-latest
 
-  #   steps:
-  #     - name: Checkout repository
-  #       uses: actions/checkout@v3
+    steps:
+      - name: Checkout repository
+        uses: actions/checkout@v3
 
-  #     - name: Setup Node.js
-  #       uses: actions/setup-node@v3
-  #       with:
-  #         node-version: '16'
+      - name: Setup Node.js
+        uses: actions/setup-node@v3
+        with:
+          node-version: '16'
 
-  #     - name: Install Yarn
-  #       run: npm install -g yarn
+      - name: Install Yarn
+        run: npm install -g yarn
 
-  #     - name: Install dependencies
-  #       run: yarn install
+      - name: Install dependencies
+        run: yarn install
 
-  #     - name: Run linting
-  #       run: yarn lint
+      - name: Run linting
+        run: yarn lint
 
-  # test:
-  #   runs-on: ubuntu-latest
+  test:
+    runs-on: ubuntu-latest
 
-  #   steps:
-  #     - name: Checkout repository
-  #       uses: actions/checkout@v3
+    steps:
+      - name: Checkout repository
+        uses: actions/checkout@v3
 
-  #     - name: Setup Node.js
-  #       uses: actions/setup-node@v3
-  #       with:
-  #         node-version: '16'
+      - name: Setup Node.js
+        uses: actions/setup-node@v3
+        with:
+          node-version: '16'
 
-  #     - name: Install Yarn
-  #       run: npm install -g yarn
+      - name: Install Yarn
+        run: npm install -g yarn
 
-  #     - name: Install dependencies
-  #       run: yarn install
+      - name: Install dependencies
+        run: yarn install
 
-  #     - name: Run unit tests
-  #       run: yarn test
+      - name: Run unit tests
+        run: yarn test
 
-  # code_scan:
-  #   name: Analyze
-  #   runs-on: ubuntu-latest
-  #   timeout-minutes: 10
-  #   strategy:
-  #     fail-fast: false
-  #     matrix:
-  #       language:
-  #         - javascript
+  code_scan:
+    name: Analyze
+    runs-on: ubuntu-latest
+    timeout-minutes: 10
+    strategy:
+      fail-fast: false
+      matrix:
+        language:
+          - javascript
 
-  #   steps:
-  #     - name: Checkout repository
-  #       uses: actions/checkout@v3
+    steps:
+      - name: Checkout repository
+        uses: actions/checkout@v3
 
-  #     - name: Initialize CodeQL
-  #       uses: github/codeql-action/init@v2
-  #       with:
-  #         languages: ${{ matrix.language }}
+      - name: Initialize CodeQL
+        uses: github/codeql-action/init@v2
+        with:
+          languages: ${{ matrix.language }}
 
-  #     - name: Autobuild
-  #       uses: github/codeql-action/autobuild@v2
+      - name: Autobuild
+        uses: github/codeql-action/autobuild@v2
 
-  #     - name: Perform CodeQL Analysis
-  #       uses: github/codeql-action/analyze@v2
-  #       with:
-  #         output: 'reports'
-  #         upload: false
+      - name: Perform CodeQL Analysis
+        uses: github/codeql-action/analyze@v2
+        with:
+          output: 'reports'
+          upload: false
 
-  #     - name: Move file to merged.sarif (CodeQL)
-  #       run: mv reports/*.sarif merged.sarif
+      - name: Move file to merged.sarif (CodeQL)
+        run: mv reports/*.sarif merged.sarif
 
-  #     - name: filter-sarif
-  #       uses: advanced-security/filter-sarif@v1
-  #       with:
-  #         # filter out all test files unless they contain a sql-injection vulnerability
-  #         patterns: |
-  #           -**/*test*.js
-  #         input: merged.sarif
-  #         output: filtered.sarif
+      - name: filter-sarif
+        uses: advanced-security/filter-sarif@v1
+        with:
+          # filter out all test files unless they contain a sql-injection vulnerability
+          patterns: |
+            -**/*test*.js
+          input: merged.sarif
+          output: filtered.sarif
 
-  #     - name: Check CodeQL results
-  #       run: |
-  #         # Parse SARIF content and check the length of "results" array
-  #         SARIF_CONTENT=$(cat filtered.sarif)
-  #         echo $SARIF_CONTENT
-  #         RESULTS_LENGTH=$(echo $SARIF_CONTENT | jq -r '.runs[0].results | length')
-  #         if [ "$RESULTS_LENGTH" -gt 0 ]; then
-  #           echo "CodeQL found issues. Failing the workflow."
-  #           exit 1
-  #         else
-  #           echo "CodeQL did not find any issues. Workflow continues."
-  #         fi
+      - name: Check CodeQL results
+        run: |
+          # Parse SARIF content and check the length of "results" array
+          SARIF_CONTENT=$(cat filtered.sarif)
+          echo $SARIF_CONTENT
+          RESULTS_LENGTH=$(echo $SARIF_CONTENT | jq -r '.runs[0].results | length')
+          if [ "$RESULTS_LENGTH" -gt 0 ]; then
+            echo "CodeQL found issues. Failing the workflow."
+            exit 1
+          else
+            echo "CodeQL did not find any issues. Workflow continues."
+          fi
 
-  # secrets_scan:
-  #   name: gitleaks
-  #   runs-on: ubuntu-latest
-  #   steps:
-  #     - name: Checkout repository
-  #       uses: actions/checkout@v3
+  secrets_scan:
+    name: gitleaks
+    runs-on: ubuntu-latest
+    steps:
+      - name: Checkout repository
+        uses: actions/checkout@v3
 
-  #     - name: Scanner
-  #       uses: gitleaks/gitleaks-action@v2
-  #       env:
-  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+      - name: Scanner
+        uses: gitleaks/gitleaks-action@v2
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
 
-  # build:
-  #   runs-on: ubuntu-latest
-  #   # needs:
-  #   #   - lint
-  #   #   - test
-  #   #   - code_scan
-  #   #   - secrets_scan
+  build:
+    runs-on: ubuntu-latest
+    needs:
+      - lint
+      - test
+      - code_scan
+      - secrets_scan
 
-  #   steps:
-  #     - name: Checkout repository
-  #       uses: actions/checkout@v3
+    steps:
+      - name: Checkout repository
+        uses: actions/checkout@v3
 
-  #     - name: Build Docker image
-  #       run: docker build -t devsecops .
+      - name: Build Docker image
+        run: docker build -t devsecops .
 
-  #     - name: Save Docker image
-  #       run: docker save devsecops -o /tmp/image.tar
+      - name: Save Docker image
+        run: docker save devsecops -o /tmp/image.tar
 
-  #     - name: Upload artifact
-  #       uses: actions/upload-artifact@v3
-  #       with:
-  #         name: image
-  #         path: /tmp/image.tar
+      - name: Upload artifact
+        uses: actions/upload-artifact@v3
+        with:
+          name: image
+          path: /tmp/image.tar
 
-  # container_scan:
-  #   runs-on: ubuntu-latest
-  #   needs:
-  #     - build
+  container_scan:
+    runs-on: ubuntu-latest
+    needs:
+      - build
 
-  #   steps:
-  #     - name: Download artifact
-  #       uses: actions/download-artifact@v3
-  #       with:
-  #         name: image
-  #         path: /tmp
+    steps:
+      - name: Download artifact
+        uses: actions/download-artifact@v3
+        with:
+          name: image
+          path: /tmp
 
-  #     - name: Load image
-  #       run: |
-  #         docker load --input /tmp/image.tar
+      - name: Load image
+        run: |
+          docker load --input /tmp/image.tar
 
-  #     - name: Run Trivy vulnerability scanner
-  #       uses: aquasecurity/trivy-action@master
-  #       with:
-  #         image-ref: devsecops
-  #         format: 'table'
-  #         exit-code: '1'
-  #         ignore-unfixed: true
-  #         vuln-type: 'os,library'
-  #         severity: 'CRITICAL,HIGH'
+      - name: Run Trivy vulnerability scanner
+        uses: aquasecurity/trivy-action@master
+        with:
+          image-ref: devsecops
+          format: 'table'
+          exit-code: '1'
+          ignore-unfixed: true
+          vuln-type: 'os,library'
+          severity: 'CRITICAL,HIGH'
 
-  # push_image_github:
-  #   runs-on: ubuntu-latest
-  #   needs:
-  #     - container_scan
+  push_image_github:
+    runs-on: ubuntu-latest
+    needs:
+      - container_scan
 
-  #   steps:
-  #     - name: Download artifact
-  #       uses: actions/download-artifact@v3
-  #       with:
-  #         name: image
-  #         path: /tmp
+    steps:
+      - name: Download artifact
+        uses: actions/download-artifact@v3
+        with:
+          name: image
+          path: /tmp
 
-  #     - name: Load image
-  #       run: |
-  #         docker load --input /tmp/image.tar
+      - name: Load image
+        run: |
+          docker load --input /tmp/image.tar
 
-  #     - name: Log in to GitHub Container Registry
-  #       run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
+      - name: Log in to GitHub Container Registry
+        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
 
-  #     - name: Push Docker image to GitHub Container Registry
-  #       env:
-  #         REPOSITORY: devsecops
-  #         IMAGE_TAG: latest
-  #       run: |
-  #         docker image tag $REPOSITORY:$IMAGE_TAG ghcr.io/${{ github.repository }}:$IMAGE_TAG
-  #         docker push ghcr.io/${{ github.repository }}
+      - name: Push Docker image to GitHub Container Registry
+        env:
+          REPOSITORY: devsecops
+          IMAGE_TAG: latest
+        run: |
+          docker image tag $REPOSITORY:$IMAGE_TAG ghcr.io/${{ github.repository }}:$IMAGE_TAG
+          docker push ghcr.io/${{ github.repository }}
 
-  # push_image_ecr:
-  #   runs-on: ubuntu-latest
-  #   # needs:
-  #   #   - container_scan
+  push_image_ecr:
+    runs-on: ubuntu-latest
+    needs:
+      - container_scan
 
-  #   steps:
-  #     - name: Download artifact
-  #       uses: actions/download-artifact@v3
-  #       with:
-  #         name: image
-  #         path: /tmp
+    steps:
+      - name: Download artifact
+        uses: actions/download-artifact@v3
+        with:
+          name: image
+          path: /tmp
 
-  #     - name: Load image
-  #       run: |
-  #         docker load --input /tmp/image.tar
+      - name: Load image
+        run: |
+          docker load --input /tmp/image.tar
 
-  #     - name: Configure AWS credentials
-  #       uses: aws-actions/configure-aws-credentials@v4
-  #       with:
-  #         aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
-  #         aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
-  #         aws-region: us-east-1
+      - name: Configure AWS credentials
+        uses: aws-actions/configure-aws-credentials@v4
+        with:
+          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
+          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+          aws-region: us-east-1
 
-  #     - name: Login to Amazon ECR
-  #       id: login-ecr
-  #       uses: aws-actions/amazon-ecr-login@v2
+      - name: Login to Amazon ECR
+        id: login-ecr
+        uses: aws-actions/amazon-ecr-login@v2
 
-  #     - name: Push Docker image to ECR
-  #       env:
-  #         REGISTRY: ${{ steps.login-ecr.outputs.registry }}
-  #         REPOSITORY: devsecops
-  #         IMAGE_TAG: latest
-  #       run: |
-  #         docker image tag $REPOSITORY:$IMAGE_TAG $REGISTRY/$REPOSITORY:$IMAGE_TAG
-  #         docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG
+      - name: Push Docker image to ECR
+        env:
+          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
+          REPOSITORY: devsecops
+          IMAGE_TAG: latest
+        run: |
+          docker image tag $REPOSITORY:$IMAGE_TAG $REGISTRY/$REPOSITORY:$IMAGE_TAG
+          docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG
 
   deploy:
     runs-on: ubuntu-latest
-    # needs:
-    #   - push_image_ecr
+    needs:
+      - push_image_ecr
     
     steps:
       - name: Checkout repository
